let projects = [
    new Project("Adventure Land Bot", "Adventure-Land-Bot",
        ["Screenshots/Game 1.png", "Screenshots/Game 2.png"],
        "Hobby", ["JavaScript"],
        `My take on automating a party for the game Adventure Land`),
    new Project("Console VSRG Trainer", "Console-VSRG-Trainer",
        ["Screenshots/In Game.png", "Screenshots/Loading Screen.png"],
        "Hobby", ["C#"],
        `My first take on a rhythm game trainer. Meaning it gives you a random combination of notes and waits for you to press the right keys.`),
    new Project("Dont Tap Bot", "Dont-Tap-Bot",
        ["Screenshots/Game.png"],
        "Hobby", ["Python"],
        `Automates the game donttap.com`),
    new Project("GoTrainer-HumanAI", "GoTrainer HumanAI",
        ["imgs/screenshot.png"],
        "Hobby", ["JavaScript", "C#"],
        `Description`),
    new Project("HSL Reviewer", "HSL-Reviewer",
        ["screenshots/Answer.png", "screenshots/Question.png", "screenshots/Reviewer.png"],
        "Hobby", ["Python"],
        `Improve your shapes and intuition in the game of Go. Tailered to your weaknesses from your own games. Using human supervised learning for 
    questions and answers of your skill level.`),
    new Project("IIDX DP Trainer", "IIDX-DP-Trainer",
        ["Screenshots/Game.png", "Screenshots/Settings.png"],
        "Hobby", ["GDScript"],
        `Acts the same as the game but waits for you to press the note combinations. Highly configurable.`),
    new Project("Noita Worldpixelscenes Visualizer", "Noita-Worldpixelscenes-Visualizer",
        ["Screenshots/Output.png"],
        "Hobby", ["C#"],
        `isualizes a file in the save files of the game Noita. It was made when the community was still figuring everything out 
the game had to offer. This application found out there was a moon. It is a simple and small program but it shows that I can make good use of 
comments and can handle errors.`),
    new Project("Name", "RepoName",
        ["Screenshots/"],
        "Hobby", ["JavaScript"],
        `Description`),
    new Project("Name", "RepoName",
        ["Screenshots/"],
        "Hobby", ["JavaScript"],
        `Description`),
    new Project("Name", "RepoName",
        ["Screenshots/"],
        "Hobby", ["JavaScript"],
        `Description`),
]
