let projects = {
	'Adventure-Land-Bot': new Project('Adventure-Land-Bot', 'Adventure Land Bot', 'master', 'Hobby',
		'2019-12-07', '2019-12-16', '2019-12-16',
		'My take on automating a party for the programming MMORPG Adventure Land.',
		['Screenshots/1-Game.png', 'Screenshots/2-Game.png'],
		['JavaScript']),
	'Console-VSRG-Trainer': new Project('Console-VSRG-Trainer', 'Console VSRG Trainer', 'master', 'Hobby',
		'2019-02-14', '2019-02-15', '2019-02-15',
		'My first take on a rhythm game trainer. It gives you a random combination of notes and waits for you to press the right keys.',
		['Screenshots/1-Loading_Screen.png', 'Screenshots/2-In_Game.png'],
		['C#']),
	'Portfolio': new Project('Portfolio', 'Portfolio', 'main', 'Hobby',
		'2025-07-31', '2025-08-02', '2025-08-02',
		'A website to show off my projects on GitHub.',
		['Screenshots/1-Page.png'],
		['JavaScript', 'Python', 'HTML', 'CSS']),
};
